---
name: Build CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - "**"

jobs:
  test:
    name: Run unit tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Run setup
        uses: ./.github/actions/setup-workspace

      - name: Run unit tests
        run: |
          just test

  build:
    name: Build binary
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Run setup
        uses: ./.github/actions/setup-workspace

      - name: Build binary
        run: |
          just build-bin "0.0.0-ci"

      - name: Run binary
        run: |
          ./opsrunner --version
          ./opsrunner --help
